/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'api.leadconnectorhq.com',
      },
      {
        protocol: 'https',
        hostname: 'beta.leadconnectorhq.com',
      },
      // Higgsfield CDN — hero images for blog posts generated by Soul Character / gpt_image_2
      {
        protocol: 'https',
        hostname: 'cdn.higgsfield.ai',
      },
      {
        protocol: 'https',
        hostname: 'cdn-higgsfield.s3.amazonaws.com',
      },
      {
        protocol: 'https',
        hostname: '*.higgsfield.ai',
      },
      // Stock-photo CDNs the forked blog skill falls back to when Higgsfield is unavailable
      {
        protocol: 'https',
        hostname: 'cdn.pixabay.com',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'images.pexels.com',
      },
    ],
    formats: ['image/webp', 'image/avif'],
  },
  pageExtensions: ['ts', 'tsx', 'js', 'jsx', 'md', 'mdx'],
  experimental: {
    optimizeCss: true,
    mdxRs: false,
  },
}

module.exports = nextConfig
